import type { NextPage } from 'next';
import { useCallback, useState } from 'react';
import Head from 'next/head';
import { testFetch } from '@sasil/common';
import MainTemplate from '@/components/templates/MainTemplate/MainTemplate';

const Home: NextPage = () => {
  const [text, setText] = useState('');
  const onClick = useCallback(async () => {
    const result = await testFetch(2);
    setText(result.data.email);
  }, []);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainTemplate />
    </div>
  );
};

export default Home;
