import Head from 'next/head';
import { getPostsAsync, PostListType } from '@sasil/common';
import MainTemplate from '@/components/templates/MainTemplate';
import { expPosts, reqPosts } from 'src/dummyData';

interface MainPageProps {
  hotReqPosts: PostListType[];
  popReqPosts: PostListType[];
  popExpPosts: PostListType[];
}

export async function getServerSideProps() {
  const [hotReq, popReq, popExp] = await Promise.all([
    getPostsAsync('request', 1, 11, 'popular', 'wait'),
    getPostsAsync('request', 1, 11, 'popular', 'all'),
    getPostsAsync('experiment', 1, 11, 'popular'),
  ]);

  const result: MainPageProps = {
    hotReqPosts: hotReq.isSuccess ? hotReq.result.list : [],
    popReqPosts: popReq.isSuccess ? popReq.result.list : [],
    popExpPosts: popExp.isSuccess ? popExp.result.list : [],
  };

  return { props: result };
}

const Home = ({ hotReqPosts, popReqPosts, popExpPosts }: MainPageProps) => (
  <div>
    <Head>
      <title>사소한 실험 플랫폼, 사실;</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <MainTemplate
      hotReqPosts={hotReqPosts.length > 0 ? hotReqPosts : reqPosts}
      popReqPosts={popReqPosts.length > 0 ? popReqPosts : reqPosts}
      popExpPosts={popExpPosts.length > 0 ? popExpPosts : expPosts}
    />
  </div>
);

export default Home;
